careerlandscape/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("clusters.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

clusters/urls.py
from django.urls import path
import django.contrib.auth.urls

from . import views

app_name = "clusters"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("manage/", views.ManageView.as_view(), name="manage"),
    path("users/<int:user_id>", views.UserView.as_view(), name="users"),
]

clusters/models/circle_model.py
from django.db import models


class Circle(models.Model):
    name = models.CharField(max_length=500)

    def __str__(self):
        return f"{self.name} Circle"

clusters/models/dimension_model.py
from django.db import models
from clusters.models.topic_model import Topic


class Dimension(models.Model):
    name = models.CharField(max_length=200)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.topic} - Dimension of Knowledge: {self.name}"

    class Meta:
        unique_together = (("name", "topic"),)

clusters/models/score_model.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from clusters.models.dimension_model import Dimension


class Score(models.Model):
    class KindOfScore(models.IntegerChoices):
        CAREER_LANDSCAPE = 0
        MOMENTUM = 1
        NEXT_STEP = 2

    person = models.ForeignKey(User, on_delete=models.CASCADE)
    dimension = models.ForeignKey(Dimension, on_delete=models.CASCADE)
    value = models.IntegerField(default=0)
    date = models.DateTimeField(default=timezone.now, blank=True)
    kind = models.IntegerField(
        choices=KindOfScore.choices, default=KindOfScore.CAREER_LANDSCAPE
    )

    def __str__(self):
        return f"[ {self.kind} Score ] {self.person} has assigned {self.value} in {self.dimension}"

clusters/models/topic_model.py
from django.db import models
from clusters.models.circle_model import Circle


class Topic(models.Model):
    name = models.CharField(max_length=500)
    circle = models.ForeignKey(Circle, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} Topic"

    class Meta:
        unique_together = (("name", "circle"),)

clusters/forms.py
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField(label="")

clusters/views/about_view.py
from django.views import generic


class AboutView(generic.TemplateView):
    template_name = "clusters/about.html"

clusters/views/index_view.py
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from clusters.models import Circle, Topic, Dimension, Score
from django.contrib.auth.models import User


@method_decorator(login_required, name="dispatch")
class IndexView(generic.TemplateView):
    template_name = "clusters/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = self.add_circles_context(context)
        return context

    def add_circles_context(self, context):
        circle_dictionary = {}
        for circle in Circle.objects.all():
            topic_value_gt, topic_dimension_eq = self.set_value_and_dimension_filters(
                circle.id
            )
            topics = Topic.objects.filter(circle=circle).distinct()
            topic_details = {
                topic.name: self.count_people_in_topic(
                    topic, topic_value_gt, topic_dimension_eq
                )
                for topic in topics
            }
            dimensions = list(
                Dimension.objects.filter(topic__in=topics)
                .distinct("name")
                .values("id", "name")
            )
            circle_dictionary[circle.name] = {
                "topics_details": topic_details,
                "dimensions": dimensions,
                "circle_id": circle.id,
                "topic_value_gt": topic_value_gt,
                "topic_dimension_eq": topic_dimension_eq,
            }
        context["circles"] = circle_dictionary
        return context

    def set_value_and_dimension_filters(self, circle_id):
        topic_value_gt = self.request.GET.get(f"topic_value_gt_{circle_id}", 0)
        topic_dimension_eq_id = int(
            self.request.GET.get(f"topic_dimension_eq_{circle_id}", "-1")
        )
        if topic_dimension_eq_id != -1:
            return (
                topic_value_gt,
                Dimension.objects.get(id=topic_dimension_eq_id).name,
            )
        return (topic_value_gt, "")

    def count_people_in_topic(self, topic, topic_value_gt=0, topic_dimension_eq=""):
        dimensions = Dimension.objects.filter(topic=topic)
        if topic_dimension_eq:
            dimensions = [dimensions.get(name=topic_dimension_eq)]
        return (
            Score.objects.filter(dimension__in=dimensions)
            .filter(value__gt=topic_value_gt, kind=0)
            .distinct("person")
            .count()
        )

clusters/views/manage_view.py
from django.views import generic
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import messages

from django.contrib.auth.models import User
from clusters.forms import UploadFileForm
from clusters.models import Circle, Topic, Dimension, Score
from clusters.lib.use_cases import ExcelUploadUseCase
from clusters.repositories import (
    UserRepository,
    CircleRepository,
    ScoreRepository,
    TopicRepository,
    DimensionRepository,
    TransactionManager,
)


@method_decorator(staff_member_required, name="dispatch")
class ManageView(generic.TemplateView):
    template_name = "clusters/manage.html"
    form_classes = {
        "upload": UploadFileForm,
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.form_classes)
        context = self.append_user_form_context(context)
        return context

    def get(self, request):
        user = self.request.GET.get("selected_user", -1)
        if user != -1:
            return HttpResponseRedirect(f"/users/{user}")
        return render(request, "clusters/manage.html", self.get_context_data())

    def post(self, request):
        upload_form = UploadFileForm(request.POST, request.FILES)
        if upload_form.is_valid():
            self.upload_form_valid()
        else:
            self.upload_form_invalid()
        return HttpResponseRedirect("/manage")

    def append_user_form_context(self, context):
        users = {
            user.id: (user.first_name, user.last_name)
            for user in User.objects.filter(is_staff=False)
        }
        context["users"] = users
        return context

    def upload_form_valid(self):
        ExcelUploadUseCase(
            UserRepository(),
            CircleRepository(),
            ScoreRepository(),
            TopicRepository(),
            DimensionRepository(),
            TransactionManager(),
            self,
        ).uploadFile(self.request.FILES["file"].file)

    def upload_form_invalid(self):
        messages.error(self.request, "File in Upload Form is not Valid")

    def uploadSuccessful(self):
        messages.success(self.request, "Upload Success!")

    def dataNotParsed(self):
        messages.error(
            self.request, "Xlsx File has incorrect format! Impossible to Proceed."
        )

    def badFileFormat(self):
        messages.error(
            self.request, "File reading generate error: please check file format."
        )

    def noCircleInDatabase(self):
        messages.error(
            self.request, "No database Circle detected. Impossible to Proceed."
        )

    def userError(self):
        messages.error(
            self.request,
            "Error in xlsx file datas: User error: User not Found or multiple user with same first name and last name",
        )

    def dataError(self):
        messages.error(
            self.request,
            "Error in xlsx file datas: Data not correct ( correct data format: dd/mm/yyyy ) ",
        )

    def onDimensionRetrievalError(self, message):
        messages.error(
            self.request, f"Consistency Error: {message} in xlsx file does not exists!"
        )

clusters/views/user_view.py
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.contrib import messages

from django.contrib.auth.models import User
from clusters.models import Circle, Topic, Dimension, Score


@method_decorator(login_required, name="dispatch")
class UserView(generic.TemplateView):
    template_name = "clusters/users.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs["user_id"]
        if (
            user_id != self.request.user.id
            and not self.request.user.is_staff
            and not self.request.user.is_superuser
        ):
            messages.error(
                self.request,
                "We are sorry, you cannot access this page. You can only access your personal page. Please check your credentials.",
            )
            return
        selected_circle = self.request.GET.get("selected_user_circle", -1)
        if selected_circle != -1:
            context["user_topics_values"] = self.add_circle_context(
                user_id, selected_circle
            )
            context["circle_name"] = Circle.objects.get(id=selected_circle).name
            context["selected_circle_id"] = Circle.objects.get(id=selected_circle).id
        person = User.objects.get(id=user_id)
        context["first_name"] = person.first_name
        context["last_name"] = person.last_name
        context["circles"] = list(Circle.objects.values_list("id", "name"))
        context["user_id"] = user_id
        if Score.objects.filter(person=person).exists():
            context["compilation_date"] = (
                Score.objects.filter(person=person).first().date
            )
        return context

    def add_circle_context(self, user_id, circle_id):
        topic_dictionary = {}
        person = User.objects.get(id=user_id)
        topics = Topic.objects.filter(circle=Circle.objects.get(id=circle_id))
        for topic in topics:
            dimensions = Dimension.objects.filter(topic=topic)
            dimensions_with_values = {}
            try:
                for dimension in dimensions:
                    dimensions_with_values[dimension.name] = [
                        Score.objects.get(
                            person=person, dimension=dimension, kind=kind
                        ).value
                        for kind in range(0, 3)
                    ]
            except ObjectDoesNotExist as _:
                return {}
            topic_dictionary[topic.name] = dimensions_with_values
        return topic_dictionary

clusters/templates/clusters/about.html
{% include "blocks/header.html" %}
<body>
{% include "blocks/navbar.html" %}

    <div class='container-fluid clearfix'>
        <div class="row">
            <div class="col-md-12">
                <div class="jumbotron m-1">
                  <h1 class="display-4 title">Welcome in Career Landscape</h1>
                  <br>
                  <p class="lead">
                      We believe that people knowledge is best represented as a landscape, with hills and valley,
                      peaks and depression, more than a ledger like is usualy represented.
                      The idea of a landscape is more linked to a non linear path ( and in some way random path )
                      of knowledge development, instead of a linear predefined path, suitable for everyone.
                  </p>
                  <hr class="my-4">
                  <p>We want a tool to have a discussion on how the person feels are is strong point and is weakness,
                        and in which topics he wants to invest time and energy in the following month.
                        It’s not a tool aimed to judge someone, or to put people in competition.</p>
                  <a class="btn btn-success btn-md float-right" href="{% url 'clusters:index' %}" role="button">Home</a>
                </div>
            </div>
        </div>
    </div>

    {% include "blocks/footer.html" %}
    {% include "blocks/scripts.html" %}

  </body>
  </html>

clusters/templates/clusters/index.html
{% include "blocks/header.html" %}
<body>
{% include "blocks/navbar.html" %}

    <div class='container-fluid clearfix'>
      <br>
      {% if circles %}
        <form action="{% url 'clusters:index' %}" method="get">
          {% for circle_name, context in circles.items %}
            <div class='row p-4'>
              <div class='col-md-4'>
                <div class="shadow card" style="width: 18rem;">
                  <div class="card-body">
                    <h3 class="card-title title">
                      <img src="{% static "clusters/images/circle-half.svg" %}" alt="" width="32" height="32" title="Documents">
                      {{ circle_name }} Circle
                    </h3>
                    <p class="card-text">
                      Here the {{ circle_name }} Circle description ..
                    </p>
                    <hr>
                    <h5 class="card-subtitle mb-2 text-muted">
                      Topics:
                    </h5>
                    {% if context.topics_details %}
                      <ul  class="list-group">
                        {% for name, number in context.topics_details.items %}
                          <li class="list-group-item d-flex justify-content-between align-items-center">
                            {{ name }} : <span class="badge dark-grey-bg text-white">{{ number }}</span>
                          </li>
                        {% endfor %}
                      </ul>
                      <hr>
                      <div class="form-group">
                        <label for="topic_value_gt_{{ context.circle_id }}">
                          Value Filter
                        </label>
                        {% if context.topic_value_gt %}
                          <p>Value Filter Setted: > {{ context.topic_value_gt }}</p>
                        {% endif %}
                        <select
                          class="form-control"
                          name="topic_value_gt_{{ context.circle_id }}"
                          id="topic_value_gt_{{ context.circle_id }}"
                        >
                          {% for topic_value in '01234'|make_list %}
                            {% if topic_value == context.topic_value_gt %}
                              <option selected='selected' value={{ topic_value }}>
                                > {{ topic_value }}
                              </option>
                            {% else %}
                              <option value={{ topic_value }}>
                                > {{ topic_value }}
                              </option>
                            {% endif %}
                          {% endfor %}
                        </select>
                      </div>
                      <hr>
                      <div class="form-group">
                        <label for="topic_dimension_eq">
                          Dimension Filter
                        </label>
                        {% if context.topic_dimension_eq %}
                          <p>Dimension Filter Setted: {{ context.topic_dimension_eq }}</p>
                        {% endif %}
                        <select
                          class="form-control"
                          name="topic_dimension_eq_{{ context.circle_id }}"
                          id="topic_dimension_eq_{{ context.circle_id }}"
                        >
                          <option value="-1">All</option>
                          {% for dimension in context.dimensions %}
                            {% if dimension.name == context.topic_dimension_eq %}
                              <option selected="selected" value="{{ dimension.id }}">
                                {{ dimension.name }}
                              </option>
                            {% else %}
                              <option value="{{ dimension.id }}">
                                {{ dimension.name }}
                              </option>
                            {% endif %}
                          {% endfor %}
                        </select>
                      </div>

                      <input type="submit">
                    {% else %}
                      <p>No Topics available.</p>
                    {% endif %}
                  </div>
                </div>
              </div>
              <div class='col-md-8'>
                <div
                  class='ml-5 media'
                  id="{{ circle_name }}"
                  style="width:500px;height:500px;"
                ></div>
              </div>
            </div>
            <hr>
          {% endfor %}
        </form>
      {% else %}
        <p>No Circle available.</p>
      {% endif %}

    </div>

    {% include "blocks/footer.html" %}

    {{ circles|json_script:"circles-json-data" }}
    <script>
      const context = JSON.parse(
        document.getElementById("circles-json-data").textContent
      );

      for (const circle in context) {
        let topics_details = context[circle]['topics_details'];
        let topics_names = Object.keys(topics_details);
        let max_range = Math.max(...(Object.values(topics_details))) + 1;
        let tooltip = topics_names.map(
          name => name + " : " + topics_details[name]
        )

        data = [{
          type: 'scatterpolar',
          r: Object.values(topics_details),
          theta: topics_names,
          fill: 'toself',
          fillcolor: 'rgba(224,0,0,0.5)',
          line : {
                color : 'rgba(224,0,0,1)',
                },
          hovertext: tooltip,
          hoverinfo: "text",
        }];

        layout = {
          polar: {
            radialaxis: {
              visible: true,
              range: [0, max_range],
              dtick: 1
            }
          },
          showlegend: false
        };

        Plotly.plot(document.getElementById(circle), data, layout);
      }
    </script>

  {% include "blocks/scripts.html" %}
  </body>
</html>

clusters/templates/clusters/user.html
<!doctype html>

{% load static %}

<html lang="en">
  <head>
    <title>Clusters</title>

    <meta charset="utf-8">
    <meta name="description" content="clusters">

    <link rel="icon" href="{% static "clusters/images/favicon.ico" %}" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    >
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Dosis|Kaushan+Script&display=swap"
    >
    <link
      rel="stylesheet"
      href="{% static "clusters/css/style.css" %}"
    >

    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  </head>

  <body>
    <nav class="navbar sticky-top navbar-expand-lg dark-grey-bg text-white">
      <a class="navbar-brand text-white title" href="{% url 'clusters:index' %}">
        Career Landscape
      </a>
      <button class="navbar-toggler" type="button"
        data-toggle="collapse" data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active text-white" href="{% url 'clusters:manage' %}">
                Manage
          </a>
          <a class="nav-item nav-link active text-white" href="{% url 'clusters:about' %}">
            About <span class="sr-only">(current)</span>
          </a>
        </div>
      </div>
      <span class="navbar-text mr-4">
        <img src="{% static "clusters/images/person-fill.svg" %}" alt="" width="32" height="32" title="Documents">
        Welcome, {{ request.user }}
      </span>
      <span class="navbar-text">
        <a class="text-light" href="{% url 'logout' %}"> Logout </a>
      </span>
    </nav>


    <div class='container-fluid clearfix'>

        <div class="row">
            <div class=" shadow card p-3 col-md-12">
                <h3 class="text-justify title text-center">
                    <img src="{% static "clusters/images/chevron-compact-left.svg" %}" alt="" width="38" height="38" title="Documents">
                   {{ first_name }} {{ last_name }}
                   <img src="{% static "clusters/images/chevron-compact-right.svg" %}" alt="" width="38" height="38" title="Documents">
                </h3>
                <hr>
                <form action="{% url 'clusters:users' user_id %}" method="get">
                    <div class="form-group">
                        <label for="selected_user_circle">
                            <h5>
                                <img src="{% static "clusters/images/circle-half.svg" %}" alt="" width="30" height="30" title="Documents">
                                User Circles
                            </h5>
                          </label>
                          <select
                          class="form-control"
                          name="selected_user_circle"
                          id="selected_user_circle"
                          >
                            {% for circle_id, circle_name in circles %}
                                <option value={{ circle_id }}>
                                  {{ circle_name }} Circle
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <input type="submit" value="See Circle">
                </form>
            </div>
        </div>
        <hr>
        {% if user_topics_values %}
            <h3 class="p-3 card title light-grey-bg text-dark text-center">
                {{circle_name}} Circle
            </h3>
            {% for topic, topic_context in user_topics_values.items %}
                <div class="row p-2">
                    <div class="col-md-5">
                        <div class="shadow card m-5 p-2" style="width: 27rem;">
                            <div class="card-body">
                                <h3 class="card-title title">
                                    <img src="{% static "clusters/images/diamond-half.svg" %}" alt="" width="30" height="30" title="Documents">
                                    {{ topic }} Topic
                                </h3>
                                <p> Here the description of {{topic}} .. </p>
                                <br>
                                <h5 class="card-subtitle mb-2 text-muted">
                                    Dimension of Knowldge:
                                </h5>
                                <table class="table table-hover p-4 " style="border-radius: 50%;">
                                    <thead class="dark-grey-bg text-white bordered">
                                        <tr>
                                            <th scope="col"><i>Name</i></th>
                                            <th scope="col"><i>Actual</i></th>
                                            <th scope="col"><i>Momentum</i></th>
                                            <th scope="col"><i>NextStep</i></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for dimension, value in topic_context.items %}
                                            <tr>
                                                <th scope="col">{{dimension}}</th>
                                                <td class="text-center bordered"><span class="badge badge-secondary red-bg">{{value.0}}</span></td>
                                                <td class="text-center bordered"><span class="badge badge-secondary yellow-bg">{{value.1}}</span></td>
                                                <td class="text-center bordered"><span class="badge badge-secondary green-bg">{{value.2}}</span></td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <br>
                                <form action="{% url 'clusters:users' user_id %}" method="get">
                                    <div class="form-check form-check-inline">
                                        {% if apply_momentum_to_radar and selected_topic == topic %}
                                        <input class="form-check-input" type="checkbox" name='momentum' checked>
                                        {% else %}
                                        <input class="form-check-input" type="checkbox" name='momentum'>
                                        {% endif %}
                                        <label class="form-check-label" for="momentum">Show Momentum Values</label>
                                    </div><br>
                                    <div class="form-check form-check-inline">
                                        {% if apply_next_step_to_radar and selected_topic == topic %}
                                            <input class="form-check-input" type="checkbox" name='next-step' checked>
                                        {% else %}
                                            <input class="form-check-input" type="checkbox" name='next-step'>
                                        {% endif %}
                                        <label class="form-check-label" for="next-step">Show Next Step Values</label>
                                    </div>
                                    <input type="hidden" name="selected_user_circle" value="{{selected_circle_id}}">
                                    <input type="hidden" name="selected_topic" value="{{topic}}">
                                    <button type="submit" class="btn dark-grey-bg text-white btn-sm float-right">Show me</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-7 pl-5">
                        <div
                        class='media'
                        id="{{ topic }}"
                        style="width:500px;height:500px;padding: 40px;"
                        ></div>
                    </div>
                </div>
                <hr style="border-width: 1px;">
            {% endfor %}
        {% elif circle_name %}
            <h3 class="p-3 card title bg-secondary text-white text-center">{{circle_name}}</h3>
            <p class="p-3 card bg-danger text-white text-center">
                <b> - information not available - </b><br> The {{circle_name}} Circle was not partially or
                entirely filled by {{ first_name }} {{ last_name }}
            </p>
        {% endif %}


    </div>
    <hr>
    <footer
      id="sticky-footer"
      class="footer fixed-bottom mt-auto py-2 dark-grey-bg text-white-50"
      style="margin-bottom:0px"
    >
      <div class="container text-center">
        <small>
          Copyright &copy; <span class="title">XPeppers, a Claranet Group Company</span>
        </small>
      </div>
    </footer>


    {{ user_topics_values|json_script:"topic-json-data" }}
    <script>
      const context = JSON.parse(
        document.getElementById("topic-json-data").textContent
      );

      for (const topic in context) {
        let dimension_details = context[topic];
        let dimension_names = Object.keys(dimension_details);
        let dimension_values = Object.values(dimension_details);
        let dimension_kind_0_values = [ dimension_values[0][0], dimension_values[1][0], dimension_values[2][0], dimension_values[3][0] ];
        let dimension_kind_1_values = [ dimension_values[0][1], dimension_values[1][1], dimension_values[2][1], dimension_values[3][1] ];
        let dimension_kind_2_values = [ dimension_values[0][2], dimension_values[1][2], dimension_values[2][2], dimension_values[3][2] ];

        let momentum = "{{ apply_momentum_to_radar }}"
        let next_step = "{{ apply_next_step_to_radar }}"
        let selected_topic = "{{ selected_topic }}"

        let data = [
            {
          type: 'scatterpolar',
          r: dimension_kind_0_values,
          theta: dimension_names,
          fill: 'toself',
          fillcolor: 'rgba(224,0,0,0.5)',
          line : {
                color : 'rgba(224,0,0,1)',
                },
          name: 'Career Landscape',}
        ];

        if (selected_topic == topic) {
            if ( momentum == "True" ){
                momentum_data = {
                    type: 'scatterpolar',
                    r: dimension_kind_1_values,
                    theta: dimension_names,
                    fill: 'toself',
                    fillcolor: 'rgba(235, 174, 66,0.5)',
                    line : {
                        color : 'rgba(235, 174, 66,1)',
                     },
                    name: 'Momentum',
                }
                data.push(momentum_data);
            }
            if ( next_step == "True" ){
                ns_data = {
                    type: 'scatterpolar',
                    r: dimension_kind_2_values,
                    theta: dimension_names,
                    fill: 'toself',
                    fillcolor: 'rgba(78,138,90,0.5)',
                    line : {
                        color : 'rgba(78,138,90,1)',
                     },
                    name: 'Next Step',
                }
                data.push(ns_data);
            }
        }

        layout = {
          polar: {
            radialaxis: {
              visible: true,
              range: [0, 5],
              dtick: 1
            }
          },
          showlegend: true
        };

        Plotly.plot(document.getElementById(topic), data, layout);
    }
    </script>


    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>